import { uniq } from '../utils.mjs';

const decodeHtml = (value = '') => String(value).replace(/<br\s*\/?>/gi, '\n').replace(/<\/p>/gi, '\n').replace(/<[^>]+>/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\s+/g, ' ').trim();
const asArray = (value) => Array.isArray(value) ? value : value ? [value] : [];
const fetchJson = async (url, fetchImpl = globalThis.fetch) => { if (typeof fetchImpl !== 'function') throw new Error('fetch implementation unavailable'); const response = await fetchImpl(url, { headers: { accept: 'application/json' } }); if (!response.ok) throw new Error(`discovery HTTP ${response.status}: ${url}`); return await response.json(); };
const sourceMeta = (source) => ({ country: source.country || null, companySize: source.companySize || source.headcount || null });

export async function discoverGreenhouse(source, fetchImpl) {
  const board = source.boardToken || source.site; if (!board) throw new Error('greenhouse source requires boardToken');
  const data = await fetchJson(`https://boards-api.greenhouse.io/v1/boards/${encodeURIComponent(board)}/jobs?content=true`, fetchImpl);
  return (data.jobs || []).map((job) => ({ externalId:String(job.id), requisitionId:job.requisition_id?String(job.requisition_id):null, company:source.company, title:job.title, canonicalUrl:job.absolute_url, applicationUrl:job.absolute_url, source:`greenhouse:${board}`, description:decodeHtml(job.content||''), locations:uniq([job.location?.name,...(job.offices||[]).map((office)=>office.location||office.name)]), workMode:source.workMode||'unknown', employmentType:source.employmentType||'unknown', postedAt:job.updated_at||null, status:'active', ...sourceMeta(source) }));
}
export async function discoverLever(source, fetchImpl) {
  const site=source.site||source.boardToken; if(!site) throw new Error('lever source requires site'); const base=source.region==='eu'?'https://api.eu.lever.co':'https://api.lever.co'; const data=await fetchJson(`${base}/v0/postings/${encodeURIComponent(site)}?mode=json`,fetchImpl);
  return asArray(data).map((job)=>({ externalId:String(job.id), company:source.company, title:job.text, canonicalUrl:job.hostedUrl||job.applyUrl, applicationUrl:job.applyUrl||job.hostedUrl, source:`lever:${site}`, description:decodeHtml(job.descriptionPlain||job.description||`${job.additionalPlain||''} ${(job.lists||[]).map((item)=>`${item.text||''} ${decodeHtml(item.content||'')}`).join(' ')}`), locations:uniq([job.categories?.location,...(job.categories?.allLocations||[])]), workMode:source.workMode||'unknown', employmentType:job.categories?.commitment||source.employmentType||'unknown', postedAt:job.createdAt?new Date(job.createdAt).toISOString():null, status:'active', ...sourceMeta(source) }));
}
export async function discoverAshby(source, fetchImpl) {
  const board=source.boardName||source.site; if(!board) throw new Error('ashby source requires boardName'); const data=await fetchJson(`https://api.ashbyhq.com/posting-api/job-board/${encodeURIComponent(board)}?includeCompensation=true`,fetchImpl);
  return (data.jobs||[]).filter((job)=>job.isListed!==false).map((job)=>({ externalId:String(job.id||job.jobUrl||job.applyUrl), company:source.company, title:job.title, canonicalUrl:job.jobUrl||job.applyUrl, applicationUrl:job.applyUrl||job.jobUrl, source:`ashby:${board}`, description:decodeHtml(job.descriptionHtml||job.description||''), locations:uniq([job.location,...(job.secondaryLocations||[]).map((item)=>item.location)]), workMode:job.isRemote?'remote':(source.workMode||'unknown'), employmentType:job.employmentType||source.employmentType||'unknown', salary:job.compensation||null, postedAt:job.publishedAt||null, status:'active', ...sourceMeta(source) }));
}
export async function discoverJsonFeed(source, fetchImpl) { if(!source.url) throw new Error('json-feed source requires url'); const data=await fetchJson(source.url,fetchImpl); const rows=Array.isArray(data)?data:(data.jobs||[]); return rows.map((job)=>({...sourceMeta(source),...job,company:job.company||source.company,companySize:job.companySize||job.headcount||source.companySize||source.headcount||null,country:job.country||job.companyCountry||source.country||null,source:job.source||`json-feed:${source.name||source.url}`})); }
export async function discoverSource(source,fetchImpl){if(source.enabled===false)return[];switch(source.kind){case'greenhouse':return discoverGreenhouse(source,fetchImpl);case'lever':return discoverLever(source,fetchImpl);case'ashby':return discoverAshby(source,fetchImpl);case'json-feed':case'aggregator':return discoverJsonFeed(source,fetchImpl);default:throw new Error(`unsupported discovery source kind: ${source.kind}`)}}
export async function discoverAll(sources,{fetchImpl=globalThis.fetch,concurrency=6}={}){const queue=(sources||[]).filter((source)=>source.enabled!==false);const results=[];const errors=[];let cursor=0;const worker=async()=>{while(cursor<queue.length){const source=queue[cursor++];try{results.push(...await discoverSource(source,fetchImpl))}catch(error){errors.push({source:source.name||source.company||source.kind,message:error.message})}}};await Promise.all(Array.from({length:Math.max(1,Math.min(concurrency,queue.length||1))},worker));return{jobs:results,errors}}
