import path from 'node:path';
import { discoverAll } from './discovery/adapters.mjs';
import { normalizeJob } from './jobs.mjs';
import { hardFilter } from './filters.mjs';
import { JobStore } from './job-store.mjs';
import { processJob } from './pipeline.mjs';
import { readJson, writeJson, ensureDir } from './utils.mjs';

const mapPipelineState=(state)=>(state==='AWAITING_APPROVAL'||state==='APPLICATION_READY')?'AWAITING_APPROVAL':state;
export class JobControlPlane {
  constructor({stateDir,profileFile,preferencesFile,sourcesFile,ats,fetchImpl=globalThis.fetch}){this.stateDir=stateDir;this.profileFile=profileFile;this.preferencesFile=preferencesFile;this.sourcesFile=sourcesFile;this.ats=ats;this.fetchImpl=fetchImpl;this.jobs=new JobStore(stateDir);this.runsFile=path.join(stateDir,'runs.json')}
  async config(){const[profile,preferences,sources]=await Promise.all([readJson(this.profileFile),readJson(this.preferencesFile,{}),readJson(this.sourcesFile,[])]);if(!profile)throw new Error(`candidate profile not found: ${this.profileFile}`);return{profile,preferences,sources}}
  async updateConfig({profile,preferences,sources}){if(profile)await writeJson(this.profileFile,profile);if(preferences)await writeJson(this.preferencesFile,preferences);if(sources)await writeJson(this.sourcesFile,sources);return{ok:true}}
  async recordRun(run){const state=await readJson(this.runsFile,{runs:[]});state.runs.unshift(run);state.runs=state.runs.slice(0,200);await writeJson(this.runsFile,state)}
  async discover(){await ensureDir(this.stateDir);const{profile,preferences,sources}=await this.config();const run={id:`discover-${Date.now()}`,type:'DISCOVERY',startedAt:new Date().toISOString(),status:'RUNNING'};const found=await discoverAll(sources,{fetchImpl:this.fetchImpl});const normalized=[];let filtered=0;for(const raw of found.jobs){try{const job=normalizeJob(raw);const filter=hardFilter(job,preferences,profile);normalized.push({...job,discoveryFilter:filter});if(!filter.pass)filtered++}catch{}}const result=await this.jobs.upsertDiscovered(normalized);for(const job of normalized.filter((item)=>item.discoveryFilter&&!item.discoveryFilter.pass))await this.jobs.patch(job.jobId,{crmStatus:'FILTERED_OUT',filterReasons:job.discoveryFilter.reasons});Object.assign(run,{status:'COMPLETED',finishedAt:new Date().toISOString(),discovered:found.jobs.length,normalized:normalized.length,newJobs:result.inserted,refreshed:result.refreshed,filtered,errors:found.errors});await this.recordRun(run);return run}
  async prepare({limit=100,jobIds=null}={}){const{profile,preferences}=await this.config();const candidates=jobIds?.length?(await Promise.all(jobIds.map((id)=>this.jobs.get(id)))).filter(Boolean):await this.jobs.list({statuses:['DISCOVERED'],limit});const runId=`prepare-${Date.now()}`;const runDir=path.join(this.stateDir,'runs',runId);const results=[];for(const job of candidates){const result=await processJob({rawJob:job,rawProfile:profile,preferences,runDir,ats:this.ats,submissionMode:'prepare-only'});const status=mapPipelineState(result.state);const checkpoint=(await readJson(path.join(runDir,'checkpoints.json'),{jobs:{}})).jobs?.[job.jobId]||{};await this.jobs.patch(job.jobId,{crmStatus:status,fitScore:result.assessment?.score??checkpoint.assessment?.score??null,fitRoute:result.assessment?.route??checkpoint.assessment?.route??null,resumePath:result.resumePath??checkpoint.resumePath??null,resumeHash:result.resumeHash??checkpoint.resumeHash??null,verification:result.verification??checkpoint.verification??null,runId});results.push({jobId:job.jobId,company:job.company,title:job.title,state:status,score:result.assessment?.score??checkpoint.assessment?.score??null})}const run={id:runId,type:'PREPARE',status:'COMPLETED',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),processed:results.length,results};await this.recordRun(run);return run}
  async runAll({prepareLimit=100}={}){const discovery=await this.discover();const preparation=await this.prepare({limit:prepareLimit});return{discovery,preparation,gate:'AWAITING_APPROVAL'}}
  async approve(jobIds='all'){const approved=await this.jobs.approve(jobIds);return approved.map(({jobId,company,title})=>({jobId,company,title}))}
  async applyApproved({limit=20}={}){const{profile,preferences}=await this.config();const jobs=await this.jobs.list({statuses:['APPROVED'],limit});const runId=`apply-${Date.now()}`;const defaultRunDir=path.join(this.stateDir,'runs',runId);const results=[];for(const job of jobs){await this.jobs.patch(job.jobId,{crmStatus:'QUEUED'});await this.jobs.patch(job.jobId,{crmStatus:'APPLICATION_IN_PROGRESS'});const runDir=job.runId?path.join(this.stateDir,'runs',job.runId):defaultRunDir;const result=await processJob({rawJob:job,rawProfile:profile,preferences,runDir,ats:this.ats,submissionMode:'auto',expectedResumeHash:job.resumeHash||null});await this.jobs.patch(job.jobId,{crmStatus:result.state,appliedAt:result.state==='SUBMITTED'?new Date().toISOString():null,applicationEmail:profile.identity?.email||null,confirmation:result.ledger?.application?.confirmation||null,applicationResult:{state:result.state,reason:result.reason||null}});results.push({jobId:job.jobId,company:job.company,title:job.title,state:result.state})}const run={id:runId,type:'APPLY',status:'COMPLETED',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),processed:results.length,results};await this.recordRun(run);return run}
  async snapshot(){const[summary,jobs,runs]=await Promise.all([this.jobs.summary(),this.jobs.list({limit:300}),readJson(this.runsFile,{runs:[]})]);return{summary,jobs,runs:runs.runs.slice(0,30)}}
}
